[package]
name = "cargo-chill"
version = "0.1.0"
edition = "2024"
license = "Beerware"
homepage = "https://crates.io/crates/cargo-chill"
repository = "https://github.com/booniepepper/cargo-chill"
description = "Chill out with some byte-counting robots."
keywords = ["terminal", "tui", "game", "incremental", "ascii-art"]

[dependencies]
crossterm = "0.29.0"
directories = "6.0.0"
ratatui = "0.29.0"
